name: open_sooq
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^0.1.2
  logger: ^1.1.0
  get: ^4.6.4
  dio: ^4.0.6
  google_fonts: ^3.0.1
  convex_bottom_bar: ^3.0.0
  banner_carousel: ^1.2.1
  connectivity_plus: ^2.3.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  google_mobile_ads: ^1.2.0
  url_launcher: ^6.1.3
  shake: ^2.1.0
  cloud_firestore: ^3.1.18
  country_pickers: ^2.0.0
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  assets:
  - assets/images/
